### ISSUE TITLE
While copying multiple video files, the connection died.

### ISSUE THREAD

**Issue by kschnier** [fastsecuredrive/fsd-issues#3]
**Describe the bug**
Startet copy of 166GB and around 200 files, after 20 files connection was gone and copy crashed

**To Reproduce**
1. Go to 'moved folders to target drive'
3. See error Log

**Expected behavior**
Copy all folders and files

**Screenshots**
![image](https://github.com/user-attachments/assets/a28e5841-765e-4dce-919f-058714212a85)

**Desktop (please complete the following information):**
 - OS: Win11
 - Arch: x64
 - Version 10.6.26120
 - Latency to SSH-Server [e.g. 60ms]

**Additional context**
Log [E_log_user.txt](https://github.com/user-attachments/files/16380658/E_log_user.txt)

**Comment by fastsecuredrive** [comment]
In latest Version 1.0.38 we cant reproduce this anymore, pls check again with latest version.
